# Python Lesson 3 — Scalars, Lists, and Control Structures
----

## 1. Python scalar types

In [2]:
import numpy as np

integer_example = 496
divisor_sum = 1 + 2 + 4 + 8 + 16 + 31 + 62 + 124 + 248

print(496 // 31)      # integer division
print(divisor_sum)


16
496


In [3]:
float_example = 0.5 * (1.0 + np.sqrt(5.0))
print(float_example)
print(type(float_example))
string_1 = 'This is a string'
string_2 = "This is another string"
string_3 = "Let's roll!"
string_4 = "She said \"Let's roll!\""

print(string_1)
print(string_3)
print(string_4)


1.618033988749895
<class 'numpy.float64'>


## 2. Strings

In [4]:
string_1 = 'This is a string'
string_2 = "This is another string"
string_3 = "Let's roll!"
string_4 = "She said \"Let's roll!\""

print(string_1)
print(string_3)
print(string_4)


This is a string
Let's roll!
She said "Let's roll!"


In [5]:
print(string_1.count("i"))
print(string_1[2])
print(string_1[2:])


3
i
is is a string


In [6]:
value = 0.5 * (1.0 + np.sqrt(5.0))
example = "The approximate value of {} is {:.5f}".format("the golden ratio", value)
print(example)


The approximate value of the golden ratio is 1.61803


## 3. Lists

In [7]:
list_example = ["This ", "is ", "a ", "list"]
print(list_example)

list_example.append("!")
print(list_example)

list_example[0] = "That "
print(list_example)


['This ', 'is ', 'a ', 'list']
['This ', 'is ', 'a ', 'list', '!']
['That ', 'is ', 'a ', 'list', '!']


In [8]:
nested = [["wasabi", "sushi"], ["taco", "burrito"]]
print(nested[1][0])

taco


In [9]:
a = [1, 2, 3]
b = a
b[0] = 100

print(a)
print(b)


[100, 2, 3]
[100, 2, 3]


In [10]:
a = [1, 2, 3]
b = list(a)
b[0] = 100

print(a)
print(b)


[1, 2, 3]
[100, 2, 3]


## 4. Conditionals (if / else)

In [11]:
x = -3

if x > 0:
    print("Positive")
elif x < 0:
    print("Negative")
else:
    print("Zero")


Negative


In [12]:
print("Big") if x > 10 else print("Small")

Small


## 5. Loops (for / while)

In [15]:
for x in "Oluwagbemiga":
    print(x)


O
l
u
w
a
g
b
e
m
i
g
a


In [16]:
total = 0
for n in range(2, 101, 2):
    total += n
print(total)


2550


In [17]:
total = 1
value = 1

while total < 5000:
    value += 1
    total *= value

print(value, total)


7 5040


## 6. Exercise 3.1

In [18]:
weight = 80      # kg
height = 1.80    # m

bmi = weight / height**2

if bmi < 15:
    category = "Very severely underweight"
elif bmi < 16:
    category = "Severely underweight"
elif bmi < 18.5:
    category = "Underweight"
elif bmi < 25:
    category = "Normal"
elif bmi < 30:
    category = "Overweight"
elif bmi < 35:
    category = "Obese Class I"
elif bmi < 40:
    category = "Obese Class II"
else:
    category = "Obese Class III"

print("BMI:", round(bmi,2))
print("Category:", category)


BMI: 24.69
Category: Normal


## 7. Exercise 3.2

In [19]:
values = range(10)

for index, value in enumerate(values):
    print("Index:", index, "Value:", value, "Square:", value**2)


Index: 0 Value: 0 Square: 0
Index: 1 Value: 1 Square: 1
Index: 2 Value: 2 Square: 4
Index: 3 Value: 3 Square: 9
Index: 4 Value: 4 Square: 16
Index: 5 Value: 5 Square: 25
Index: 6 Value: 6 Square: 36
Index: 7 Value: 7 Square: 49
Index: 8 Value: 8 Square: 64
Index: 9 Value: 9 Square: 81


## 8. Exercise 3.3

In [22]:
i = 0
while i <= 1.00000000000000000000000000000000000001:
    print(round(i,2))
    i += 0.01


0
0.01
0.02
0.03
0.04
0.05
0.06
0.07
0.08
0.09
0.1
0.11
0.12
0.13
0.14
0.15
0.16
0.17
0.18
0.19
0.2
0.21
0.22
0.23
0.24
0.25
0.26
0.27
0.28
0.29
0.3
0.31
0.32
0.33
0.34
0.35
0.36
0.37
0.38
0.39
0.4
0.41
0.42
0.43
0.44
0.45
0.46
0.47
0.48
0.49
0.5
0.51
0.52
0.53
0.54
0.55
0.56
0.57
0.58
0.59
0.6
0.61
0.62
0.63
0.64
0.65
0.66
0.67
0.68
0.69
0.7
0.71
0.72
0.73
0.74
0.75
0.76
0.77
0.78
0.79
0.8
0.81
0.82
0.83
0.84
0.85
0.86
0.87
0.88
0.89
0.9
0.91
0.92
0.93
0.94
0.95
0.96
0.97
0.98
0.99


## 9. Exercise 3.4

In [23]:
a = 0.3 + 0.6
b = 0.9

print("Direct comparison:", a == b)
print("np.isclose:", np.isclose(a, b))


Direct comparison: False
np.isclose: True


## 10. Exercise 3.5

In [25]:
metdata_orig = np.loadtxt("T_Alicante_EM.csv", delimiter=",", skiprows=1)
years = metdata_orig[:,0]
temp_data = metdata_orig[:,1:]


threshold = 30
counter = 0

for i in range(temp_data.shape[0]):
    if temp_data[i,:].max() >= threshold:
        print("Extreme year:", int(years[i]))
        counter += 1

print("Total extreme years:", counter)


Total extreme years: 0


## 11. Exercise 3.6

In [26]:
x = np.arange(9).reshape(3,3)
print(x)

positions = np.where(x > 5)
print("Positions:", positions)

print("Values:", x[positions])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Positions: (array([2, 2, 2]), array([0, 1, 2]))
Values: [6 7 8]
